version: '3.8'
services:
  onlyoffice-documentserver:
    build:
      context: .
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
    ports:
      - '89:80'
      - '8553:443'
    stdin_open: true
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - onlyoffice_example_files:/var/www/onlyoffice/documentserver-example/public/files
      - onlyoffice_fonts:/usr/share/fonts

  onlyoffice-rabbitmq:
    image: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  onlyoffice-postgresql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  onlyoffice_data:
  onlyoffice_logs:
  onlyoffice_cache:
  onlyoffice_example_files:
  onlyoffice_fonts:
  postgresql_data:
  rabbitmq_data:
